# Generated by Django 6.0 on 2025-12-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleTable',
        ),
    ]
