# Generated by Django 6.0 on 2025-12-11 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0004_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='task',
            name='decription',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
